### ISSUE TITLE
Error in last time step when running the example

### ISSUE THREAD

**Issue by kristianfoerster** [mothlight/Target-Java.v2#1]
Hi @mothlight , Thank you for developing Target! I encountered an error while running the example:

starting loop 23086 Sun Nov 28 22:00:00 CET 2004 23086
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index 23087 out of bounds for length 23087
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at Target.TargetModule.modelRun(TargetModule.java:438)
	at Target.RunToolkit.run(RunToolkit.java:175)
	at Target.RunToolkit.main(RunToolkit.java:71)

**Comment by mothlight** [comment]
It shouldn't be a problem. It just ran out of forcing data at the end of the run, the last hour. It will still have generated the results for all the previous timesteps. But yes, I should probably fix the example.

Happy to discuss more by email. Contact information is here https://mothlight.github.io/
